version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    # Add any other configuration specific to the frontend service

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "weeb"
      POSTGRES_PASSWORD: "weeb"
      POSTGRES_DB: "weeb"
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    # Add any other configuration specific to the PostgreSQL service

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_USER: "weeb"
      DB_PASSWORD: "weeb"
      DB_NAME: "weeb"
      DB_PORT: 5432
      DB_HOST: postgres
    depends_on:
      - postgres
    # Add any other configuration specific to the backend service
volumes:
  database_data:
    driver: local
