version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    # Add any other configuration specific to the frontend service

  mongodb:
    image: mongo:6.0.13-jammy
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    # Add any other configuration specific to the MongoDB service

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongodb:27017/main"
    env_file: # No file specified, it will use environment variables from the shell
    depends_on:
      - mongodb
    # Add any other configuration specific to the backend service
volumes:
  mongodb_data:
    driver: local
