apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:6.0.13-jammy
        ports:
        - containerPort: 27017
          name: mongodb-port
        imagePullPolicy: Never  # Set the imagePullPolicy to Never
